//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "classes_teachers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub teacher_id: i32,
    #[sea_orm(primary_key)]
    pub class_id: i32,
    #[sea_orm(primary_key)]
    pub study_group_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::classes::Entity",
        from = "Column::ClassId",
        to = "super::classes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Classes,
    #[sea_orm(
        belongs_to = "super::study_groups::Entity",
        from = "Column::StudyGroupId",
        to = "super::study_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    StudyGroups,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::TeacherId",
        to = "super::teachers::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teachers,
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::study_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudyGroups.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
