//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discipline_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub department_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::disciplines::Entity")]
    Disciplines,
    #[sea_orm(
        belongs_to = "super::subdivisions::Entity",
        from = "Column::DepartmentId",
        to = "super::subdivisions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Subdivisions,
}

impl Related<super::disciplines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Disciplines.def()
    }
}

impl Related<super::subdivisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subdivisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
