//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod attestations;
pub mod attestations_examiners;
pub mod class_kinds;
pub mod classes;
pub mod classes_teachers;
pub mod curriculums;
pub mod discipline_types;
pub mod disciplines;
pub mod person_sessions;
pub mod persons;
pub mod sea_orm_active_enums;
pub mod students;
pub mod students_attestations;
pub mod study_groups;
pub mod study_groups_curriculums;
pub mod study_groups_students;
pub mod subdivision_attributes;
pub mod subdivision_members;
pub mod subdivisions;
pub mod subdivisions_attributes;
pub mod teachers;
pub mod universities;
