//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "person_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub person_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub metadata: String,
    #[sea_orm(unique)]
    pub refresh_token: String,
    pub expires_at_in_seconds: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::persons::Entity",
        from = "Column::PersonId",
        to = "super::persons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persons,
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
