//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::attestations::Entity as Attestations;
pub use super::attestations_examiners::Entity as AttestationsExaminers;
pub use super::class_kinds::Entity as ClassKinds;
pub use super::classes::Entity as Classes;
pub use super::classes_teachers::Entity as ClassesTeachers;
pub use super::curriculums::Entity as Curriculums;
pub use super::discipline_types::Entity as DisciplineTypes;
pub use super::disciplines::Entity as Disciplines;
pub use super::person_sessions::Entity as PersonSessions;
pub use super::persons::Entity as Persons;
pub use super::students::Entity as Students;
pub use super::students_attestations::Entity as StudentsAttestations;
pub use super::study_groups::Entity as StudyGroups;
pub use super::study_groups_curriculums::Entity as StudyGroupsCurriculums;
pub use super::study_groups_students::Entity as StudyGroupsStudents;
pub use super::subdivision_attributes::Entity as SubdivisionAttributes;
pub use super::subdivision_members::Entity as SubdivisionMembers;
pub use super::subdivisions::Entity as Subdivisions;
pub use super::subdivisions_attributes::Entity as SubdivisionsAttributes;
pub use super::teachers::Entity as Teachers;
pub use super::universities::Entity as Universities;
