//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "students")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub person_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::persons::Entity",
        from = "Column::PersonId",
        to = "super::persons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persons,
    #[sea_orm(has_many = "super::students_attestations::Entity")]
    StudentsAttestations,
    #[sea_orm(has_many = "super::study_groups_students::Entity")]
    StudyGroupsStudents,
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persons.def()
    }
}

impl Related<super::students_attestations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentsAttestations.def()
    }
}

impl Related<super::study_groups_students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudyGroupsStudents.def()
    }
}

impl Related<super::study_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::study_groups_students::Relation::StudyGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::study_groups_students::Relation::Students.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
