//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "study_groups_curriculums")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub study_group_id: i32,
    #[sea_orm(primary_key)]
    pub curriculum_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::curriculums::Entity",
        from = "Column::CurriculumId",
        to = "super::curriculums::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Curriculums,
    #[sea_orm(
        belongs_to = "super::study_groups::Entity",
        from = "Column::StudyGroupId",
        to = "super::study_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    StudyGroups,
}

impl Related<super::curriculums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Curriculums.def()
    }
}

impl Related<super::study_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudyGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
