//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subdivision_members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub subdivision_id: i32,
    pub person_id: i32,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::persons::Entity",
        from = "Column::PersonId",
        to = "super::persons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persons,
    #[sea_orm(
        belongs_to = "super::subdivisions::Entity",
        from = "Column::SubdivisionId",
        to = "super::subdivisions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Subdivisions,
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persons.def()
    }
}

impl Related<super::subdivisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subdivisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
