//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subdivisions_attributes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub attribute_id: i32,
    #[sea_orm(primary_key)]
    pub subdivision_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::subdivision_attributes::Entity",
        from = "Column::AttributeId",
        to = "super::subdivision_attributes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SubdivisionAttributes,
    #[sea_orm(
        belongs_to = "super::subdivisions::Entity",
        from = "Column::SubdivisionId",
        to = "super::subdivisions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Subdivisions,
}

impl Related<super::subdivision_attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubdivisionAttributes.def()
    }
}

impl Related<super::subdivisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subdivisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
