//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::TeacherKind;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "teachers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub person_id: i32,
    pub kind: TeacherKind,
    pub department_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attestations_examiners::Entity")]
    AttestationsExaminers,
    #[sea_orm(has_many = "super::classes_teachers::Entity")]
    ClassesTeachers,
    #[sea_orm(
        belongs_to = "super::persons::Entity",
        from = "Column::PersonId",
        to = "super::persons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persons,
    #[sea_orm(
        belongs_to = "super::subdivisions::Entity",
        from = "Column::DepartmentId",
        to = "super::subdivisions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Subdivisions,
}

impl Related<super::attestations_examiners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttestationsExaminers.def()
    }
}

impl Related<super::classes_teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassesTeachers.def()
    }
}

impl Related<super::persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persons.def()
    }
}

impl Related<super::subdivisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subdivisions.def()
    }
}

impl Related<super::attestations::Entity> for Entity {
    fn to() -> RelationDef {
        super::attestations_examiners::Relation::Attestations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::attestations_examiners::Relation::Teachers
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
