[workspace]
resolver = "2"

members = [
    "app",
    "utils",
    "utils_macros",
    # "adapters",
  # "api",
]

[workspace.dependencies]
async-trait = { version = "0.1.73" }
anyhow = { version = "1.0.75" }
domain = { path = "../domain" }
thiserror = { version = "1.0.49" }
