[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0.49" }
anyhow = { version = "1.0.75" }
async-trait = { version = "0.1.73" }
utils = { path = "../utils" }
time = { version = "0.3.30" }
