[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0.49" }
serde = { version = "1.0.188", features = ["derive"] }
anyhow.workspace = true
async-trait.workspace = true
domain.workspace = true
