[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../../domain" }
thiserror = { version = "1.0.49" }
anyhow = { version = "1.0.75" }
serde = { version = "1.0.188", features = ["derive"] }
