[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
thiserror.workspace = true
anyhow.workspace = true
async-trait.workspace = true
di = { path = "../di" }
